"""add personal_relevance to events

Revision ID: 1605d98fe6c0
Revises: 6ee3000752ee
Create Date: 2026-08-17 23:57:30.213045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1605d98fe6c0'
down_revision: Union[str, Sequence[str], None] = '6ee3000752ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'events',
        sa.Column('personal_relevance', sa.Float(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'personal_relevance')
    # ### end Alembic commands ###
