"""add content_candidates

Revision ID: 8e3839504188
Revises: 1605d98fe6c0
Create Date: 2026-08-18 00:04:36.817876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3839504188'
down_revision: Union[str, Sequence[str], None] = '1605d98fe6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('angle', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('personal_score', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_candidates_event_id'), 'content_candidates', ['event_id'], unique=False)
    op.create_index(op.f('ix_content_candidates_viral_score'), 'content_candidates', ['viral_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_candidates_viral_score'), table_name='content_candidates')
    op.drop_index(op.f('ix_content_candidates_event_id'), table_name='content_candidates')
    op.drop_table('content_candidates')
    # ### end Alembic commands ###
