"""publish workflow: post status + post_predictions

Revision ID: 8f9f5d0eb3cc
Revises: ee94ac35d812
Create Date: 2026-08-18 13:36:50.253988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f9f5d0eb3cc'
down_revision: Union[str, Sequence[str], None] = 'ee94ac35d812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=True),
    sa.Column('algorithm_version', sa.String(length=64), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('x_simulation', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('predicted_impressions', sa.Integer(), nullable=True),
    sa.Column('predicted_likes', sa.Integer(), nullable=True),
    sa.Column('predicted_replies', sa.Integer(), nullable=True),
    sa.Column('predicted_reposts', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_predictions_post_id'), 'post_predictions', ['post_id'], unique=False)
    op.add_column(
        'posts',
        sa.Column('status', sa.String(length=16), nullable=False, server_default='posted'),
    )
    op.add_column(
        'posts',
        sa.Column('origin', sa.String(length=16), nullable=False, server_default='imported'),
    )
    op.add_column('posts', sa.Column('angle', sa.String(length=32), nullable=True))
    op.add_column('posts', sa.Column('event_id', sa.UUID(), nullable=True))
    op.alter_column('posts', 'external_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.alter_column('posts', 'external_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('posts', 'event_id')
    op.drop_column('posts', 'angle')
    op.drop_column('posts', 'origin')
    op.drop_column('posts', 'status')
    op.drop_index(op.f('ix_post_predictions_post_id'), table_name='post_predictions')
    op.drop_table('post_predictions')
    # ### end Alembic commands ###
