"""add profile_snapshots

Revision ID: c87731095685
Revises: a6d9f615bc8c
Create Date: 2026-08-18 16:30:49.753453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87731095685'
down_revision: Union[str, Sequence[str], None] = 'a6d9f615bc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('tweets', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_snapshots_captured_at'), 'profile_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_profile_snapshots_handle'), 'profile_snapshots', ['handle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_snapshots_handle'), table_name='profile_snapshots')
    op.drop_index(op.f('ix_profile_snapshots_captured_at'), table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    # ### end Alembic commands ###
